version: '3.8'
services:
  kafka:
      image: bitnami/kafka:latest
      container_name: kafka
      environment:
        - KAFKA_CFG_NODE_ID=1
        - KAFKA_CFG_PROCESS_ROLES=broker,controller
        - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
        - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
        - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
        - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - ALLOW_PLAINTEXT_LISTENER=yes
      ports:
        - "9094:9094"
      # networks:
      #   - kafka-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - '8080:8080'
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_READONLY=false
      - KAFKA_CLUSTERS_0_TOPIC_AUTO_CREATE=true
    # networks:
    #   - kafka-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  order-service:
    build: ./order-service
    ports:
      - "3001:3000"
    environment:
      KAFKA_BROKER: kafka:9092
      REDIS_HOST: redis
    depends_on:
      - kafka
      - redis

  inventory-service:
    build: ./inventory-service
    ports:
      - "3002:3000"
    environment:
      KAFKA_BROKER: kafka:9092
      REDIS_HOST: redis
    depends_on:
      - kafka
      - redis

  payment-service:
    build: ./payment-service
    ports:
      - "3003:3000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka

  email-service:
    build: ./email-service
    ports:
      - "3004:3000"
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
volumes:
  kafka_data:
    driver: local
